### ISSUE TITLE
Automap-chan triggers Malwarebytes on First Use

### ISSUE THREAD

**Issue by The0Show** [dudehacker/Automap-chan#2]
The application started fine, and I was able to load a MIDI, but once I clicked "Create Beatmap", the software closed and I got this message from Malwarebytes.

![image](https://user-images.githubusercontent.com/62229104/103453078-09eff380-4ca4-11eb-84b1-61d243835468.png)

For some reason, it only triggered once, but it could turn away future users.

**Comment by sortedcord** [comment]
Probably a false positive...

**Comment by dudehacker** [comment]
you can see the source code , nothing bad... no idea which part trigger it

**Comment by The0Show** [comment]
now that im older, this was stupid, im sorry

closing this
