### ISSUE TITLE
Deprecated code: corrupted beatmap is exported

### ISSUE THREAD

**Issue by sortedcord** [dudehacker/Automap-chan#3]
Firstly, I just wanted to applaud you for this project I really liked the initiative and the work put into this even thought this was a couple of years old not sure if this is actively being developed or anything like that, but as a request, I would really like for this to work again, if it's possible...

The program opens fine, but as soon as export a beatmap, I am met with this- 
![image](https://user-images.githubusercontent.com/37407370/134793952-81e70b03-2648-47d4-93c1-1b7b0b15ba46.png)

This is what I saw in the logs-
![image](https://user-images.githubusercontent.com/37407370/134794058-cb2fe365-239a-4e2a-9c69-5bf981f32482.png)

This is probably something related to the imported modules and not the actual source code of the program itself. I'm not a java developer so I might be wrong. But I hope someone will look into this...

**Comment by dudehacker** [comment]
seems related to your java environment, I am using JRE 1.8.0

try that instead if you dont have it https://www.oracle.com/java/technologies/downloads/#java8

**Comment by sortedcord** [comment]
That fixed it. Cheers!
